{
 "title": "Demo Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Country with Highest Population",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT Name, Population\r\nFROM world.country\r\nWHERE Population = (SELECT MAX(Population) FROM world.country); "
    }
   ]
  },
  {
   "title": "Country wise Surface Area ",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT SurfaceArea, Code2 FROM world.country LIMIT 10"
    }
   ]
  },
  {
   "title": "Countries with Lowest Population",
   "type": "table",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT Name, Population\r\nFROM world.country\r\nWHERE Population = (SELECT MIN(Population) FROM world.country); "
    }
   ]
  },
  {
   "title": "Languages in India",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT Language, Percentage FROM world.countrylanguage WHERE CountryCode LIKE 'IND'"
    }
   ]
  },
  {
   "title": "Country wise Population",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 9, "x": 5, "y": 6 },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT Population, Code FROM world.country LIMIT 10"
    }
   ]
  },
  {
   "title": "Country with Most Spoken Language",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT Language, CountryCode\r\nFROM world.countrylanguage\r\nWHERE Percentage = (SELECT MAX(Percentage) FROM world.countrylanguage WHERE  Language = 'English');"
    }
   ]
  },
  {
   "title": "Languages in USA",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT Language, Percentage FROM world.countrylanguage WHERE CountryCode = 'USA'"
    }
   ]
  },
  {
   "title": "City with Highest Population",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "world",
     "rawSql": "SELECT District, CountryCode, Population\r\nFROM world.city\r\nWHERE Population = (SELECT MAX(Population) FROM world.city); "
    }
   ]
  }
 ]
}